package org.playground.drools.DroolsTutotial.rules;

import org.playground.drools.DroolsTutotial.Person;

	rule "Good Morning"
	when
		person: Person(time >= 0, time < 12)
	then
		person.setGreet("Good Morning " + person.getName());
        System.out.println(person);

	end

	rule "Good Afternoon"
	when
		person: Person(time >= 12, time < 16)
	then
		person.setGreet("Good Afternoon " + person.getName());
        System.out.println(person);
	end
	
	rule "Good Night"
	when
		person: Person(time >= 16, time <= 24)
	then
		person.setGreet("Good Night " + person.getName());
        System.out.println(person);
	end
	